---
output: html_document
---

https://defillama.com/docs/api

```{r setup, include=FALSE}
rm(list = ls())

library("tidyverse")
library("httr2")

defi_llama_protocols = function(provider_url){
  request_output = request(str_c(provider_url)) %>% 
    req_headers('accept' = "*/*",
                'content-type' = "application/json") %>%
    #req_body_raw(str_c('{"id": 1,"jsonrpc": "2.0", "method": "net_listening"}')) %>% 
    req_perform() %>%
    resp_body_json()
  request_output
}

chain_tvl_url = "https://api.llama.fi/chains"
chain_tvl_list = defi_llama_protocols(chain_tvl_url)
chain_tvl_df = data.frame(Reduce(rbind, chain_tvl_list)) %>% 
  select(name, tvl, everything()) %>% 
  unnest_longer(name) %>% 
  unnest_longer(tvl) %>% 
  unnest_longer(gecko_id) %>% 
  unnest_longer(tokenSymbol) %>% 
  unnest_longer(cmcId) %>% 
  unnest_longer(chainId) %>% 
  mutate(tvl = format(tvl, scientific = FALSE)) %>% 
  arrange(desc(tvl))

chain_tvl_df 
```

```{r}
protocol_tvl_url = "https://api.llama.fi/protocols"
protocol_tvl_list = defi_llama_protocols(protocol_tvl_url)
protocol_tvl_df = data.frame(Reduce(rbind, protocol_tvl_list))

protocol_tvl = protocol_tvl_df %>% 
  unnest_longer(name) %>% 
  unnest_longer(symbol) %>% 
  unnest_longer(gecko_id) %>% 
  select(name, url, symbol, gecko_id, tvl) %>% 
  arrange(name)
  
`%notin%` <- Negate(`%in%`)

chk_tvl = protocol_tvl %>% 
  filter(symbol %notin% c("STAKE", "SILO", "TRDL", 
                          "GEAR", "MATIC", "SWP", "JPEG"),
         !grepl("list", tvl),
         !grepl("NULL", tvl)) %>% 
  mutate(tvl = unlist(tvl),
         tvl = as.numeric(tvl),
         tvl = format(tvl, scientific = FALSE)) %>% 
  arrange(desc(tvl))


  #unnest_longer(cmcId) %>% 
  unnest_longer(twitter) %>% 
  filter(grepl("http", url)) %>% 
  unnest_longer(url) %>% 
  select(name, url, symbol, gecko_id, cmcId, twitter)

tvl_data %>% 
  filter(name %in% c("Uniswap V2")) %>% 
  select(name, symbol, url, tvl) %>% 
  unnest_longer(tvl) 



```

```{r}
chk = tvl_data %>% 
  filter(name %in% c("Uniswap V2", "Uniswap V2")) %>% 
  select(name, symbol, url, tvl) %>% 
  filter(grepl("list", tvl)) 

chk %>% 
  filter(!grepl("list", tvl)) %>% 
  filter(!grepl("NULL", tvl)) %>% 
  mutate(tvl = unlist(tvl)) 

tvl_list

chk = tvl_data %>% 
  slice(1:10)
chk

#unnest_longer(tvl)
```


```{r}
defi_llama_dex_data = function(dex_name){
  request_output = request(str_c('https://api.llama.fi/summary/dexs/', dex_name,
  '?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyVolume')) %>% 
    req_headers('accept' = "*/*", 'content-type' = "application/json") %>%
    #req_body_raw(str_c('{"id": 1,"jsonrpc": "2.0", "method": "net_listening"}')) %>% 
    req_perform() %>%
    resp_body_json()
  request_output
}

dex_list = defi_llama_dex_data("uniswap")
dex_list$totalDataChartBreakdown
dex_df = data.frame(
  name = dex_list$name,
  github = dex_list$github[[1]],
  twitter = dex_list$twitter,
  total_last_day = dex_list$total24h,
  total_all_time = dex_list$totalAllTime
); dex_df
```

```{r}
defi_llama_volume = function(volume_type){
  request_output = request(str_c('https://api.llama.fi/overview/dexs?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=',volume_type)) %>% 
    req_headers('accept' = "*/*", 'content-type' = "application/json") %>%
    #req_body_raw(str_c('{"id": 1,"jsonrpc": "2.0", "method": "net_listening"}')) %>% 
    req_perform() %>%
    resp_body_json()
  request_output
}

total_volume_list = defi_llama_volume("totalVolume")
total_volume_df = data.frame(Reduce(rbind, total_volume_list$protocols))

chains_data = total_volume_df %>% 
  unnest_longer(c(name, chains)) %>%
  select(name, chains) %>% 
  unnest(chains) %>% 
  group_by(name) %>%
  summarise(chains = paste(chains, collapse = ", "))

total_volume_data = total_volume_df %>% 
  unnest_longer(c(name, total24h, total7d, total30d, total1y)) %>% # change_1d, change_7d
  select(name, total24h, total7d, total30d, total1y) # change_1d, change_7d

total_volume_data
```

```{r}
volume_data = total_volume_data %>% 
  rename(protocol_versions = name) %>% 
  mutate(name = protocol_versions,
         name = str_replace_all(name, "QuickSwap", "Quickswap"),
         name = str_replace_all(name, "ZyberSwap", "Zyberswap"),
         name = str_replace_all(name, " V1", ""),
         name = str_replace_all(name, " V2", ""),
         name = str_replace_all(name, " V3", ""),
         name = str_replace_all(name, " V4", ""),
         name = str_replace_all(name, " AMM", ""),
         name = str_replace_all(name, " Classic", ""),
         name = str_replace_all(name, " Dex", ""),
         name = str_replace_all(name, " Concentrated Liquidity", ""),
         name = str_replace_all(name, " Stableswap", ""),
         name = str_replace_all(name, " StableSwap", ""),
         name = str_replace_all(name, " Stable", ""),
         name = str_replace_all(name, " Elastic", ""),
         name = str_replace_all(name, " Derivatives", ""),
         name = str_replace_all(name, " Liquidity Hub", ""),
         name = str_replace_all(name, ".Trade", "")) %>% 
  select(name, protocol_versions, everything()) %>% 
  group_by(name) %>%
  summarise(total24h = sum(total24h), 
            total7d = sum(total7d), 
            total30d = sum(total30d), 
            total1y = sum(total1y))

versions_data = total_volume_data %>% 
  rename(protocol_versions = name) %>% 
  mutate(name = protocol_versions,
         name = str_replace_all(name, "QuickSwap", "Quickswap"),
         name = str_replace_all(name, "ZyberSwap", "Zyberswap"),
         name = str_replace_all(name, " V1", ""),
         name = str_replace_all(name, " V2", ""),
         name = str_replace_all(name, " V3", ""),
         name = str_replace_all(name, " V4", ""),
         name = str_replace_all(name, " AMM", ""),
         name = str_replace_all(name, " Classic", ""),
         name = str_replace_all(name, " Dex", ""),
         name = str_replace_all(name, " Concentrated Liquidity", ""),
         name = str_replace_all(name, " Stableswap", ""),
         name = str_replace_all(name, " StableSwap", ""),
         name = str_replace_all(name, " Stable", ""),
         name = str_replace_all(name, " Elastic", ""),
         name = str_replace_all(name, " Derivatives", ""),
         name = str_replace_all(name, " Liquidity Hub", ""),
         name = str_replace_all(name, ".Trade", "")) %>%
  select(name, protocol_versions, everything()) %>% 
  group_by(name) %>%
  summarise(protocol_versions = paste(protocol_versions, collapse = ", "))
  
chains_data = total_volume_df %>% 
  rename(protocol_versions = name) %>% 
  mutate(name = protocol_versions,
         name = str_replace_all(name, "QuickSwap", "Quickswap"),
         name = str_replace_all(name, "ZyberSwap", "Zyberswap"),
         name = str_replace_all(name, " V1", ""),
         name = str_replace_all(name, " V2", ""),
         name = str_replace_all(name, " V3", ""),
         name = str_replace_all(name, " V4", ""),
         name = str_replace_all(name, " AMM", ""),
         name = str_replace_all(name, " Classic", ""),
         name = str_replace_all(name, " Dex", ""),
         name = str_replace_all(name, " Concentrated Liquidity", ""),
         name = str_replace_all(name, " StableSwap", ""),
         name = str_replace_all(name, " Stableswap", ""),
         name = str_replace_all(name, " Stable", ""),
         name = str_replace_all(name, " Elastic", ""),
         name = str_replace_all(name, " Derivatives", ""),
         name = str_replace_all(name, " Liquidity Hub", ""),
         name = str_replace_all(name, ".Trade", "")) %>% 
  unnest_longer(c(name, chains)) %>%
  distinct(name, chains) %>% 
  group_by(name) %>%
  summarise(chains = paste(chains, collapse = ", ")) 
  
combined_data = versions_data %>% 
  left_join(chains_data, by = "name") %>% 
  select(name, protocol_versions, chains, everything()) %>% 
  left_join(volume_data, by = "name")

combined_data; rm(volume_data, versions_data, chains_data)
```














