---
title: "Untitled"
author: "BK"
date: "2023-12-20"
output: html_document
---

https://docs.moralis.io/web3-data-api/evm/reference/get-wallet-token-balances

```{r setup, include=FALSE}
rm(list = ls())

library("tidyverse")
library("janitor")
library("coinmarketcapr")
library("notionR")
library("curlconverter")
library("jsonlite")
library("httr")

#my_endpoint = 'https://deep-index.moralis.io/api/v2.2/'
my_api_key = 

get_eth_balance = function(wallet, chain){
  library("httr")
  library("stringr")
  get_json_data = httr::GET(stringr::str_c('https://deep-index.moralis.io/api/v2.2/', wallet, "/balance?chain=", "eth"),
                            accept_json(), 
                            add_headers('X-API-Key' = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjU5ZTNjZGVkLWZiNzEtNDU4Yy05ZDlhLTk5ZmZlODE3OTlmNyIsIm9yZ0lkIjoiMzY5MDAxIiwidXNlcklkIjoiMzc5MjM5IiwidHlwZUlkIjoiYWU5NjU5NGYtZmRhZC00ZWFhLWI3YzctNDc2NGU2Y2RkOGYzIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MDMxMDg2OTcsImV4cCI6NDg1ODg2ODY5N30.r1sDrVe-Buz87RY5g_tRLHftnYw8hxC81LUtpxhvrlo'))
  unfold_json_data = content(get_json_data, type="application/json")
  bind_json_data = dplyr::bind_rows(unfold_json_data) %>% 
    mutate(balance = as.numeric(balance)/as.numeric((10^18)),
           symbol = "ETH",
           wallet_address = wallet) %>% 
    select(wallet_address, balance, symbol) 
  bind_json_data
}

get_erc20_balance = function(wallet, chain){
  library("httr")
  library("stringr")
  get_json_data = httr::GET(stringr::str_c('https://deep-index.moralis.io/api/v2.2/', wallet, "/erc20?chain=", chain),
                            accept_json(), 
                            add_headers('X-API-Key' = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjU5ZTNjZGVkLWZiNzEtNDU4Yy05ZDlhLTk5ZmZlODE3OTlmNyIsIm9yZ0lkIjoiMzY5MDAxIiwidXNlcklkIjoiMzc5MjM5IiwidHlwZUlkIjoiYWU5NjU5NGYtZmRhZC00ZWFhLWI3YzctNDc2NGU2Y2RkOGYzIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MDMxMDg2OTcsImV4cCI6NDg1ODg2ODY5N30.r1sDrVe-Buz87RY5g_tRLHftnYw8hxC81LUtpxhvrlo'))
  unfold_json_data = content(get_json_data, type="application/json")
  bind_json_data = dplyr::bind_rows(unfold_json_data) %>% 
    mutate(balance = as.numeric(balance)/as.numeric((10^as.numeric(decimals))),
           wallet_address = wallet) %>% 
    select(wallet_address, balance, symbol) 
  bind_json_data
}

get_wallet_balance = function(wallet, chain){
  all_balances = bind_rows(get_eth_balance(wallet, chain), 
                           get_erc20_balance(wallet, chain))
  all_balances
}
```

```{r}
wallet_balances = bind_rows(
  
  # 0xkramer.eth
  get_eth_balance("0xfdd76F03A234AdEb992F5283a48094569b685228"),
  get_erc20_balance("0xfdd76F03A234AdEb992F5283a48094569b685228", "eth"),
  # bkramer.eth
  get_eth_balance("0x4deb12354ea92958fa11fC8c124A9F12B61B8Ab4"),
  get_erc20_balance("0x4deb12354ea92958fa11fC8c124A9F12B61B8Ab4", "eth"),
  get_erc20_balance("0x4deb12354ea92958fa11fC8c124A9F12B61B8Ab4", "arbitrum"),
  # brandonkramer.eth
  get_eth_balance("0xD4689dF10d248FDDC4C16fb6Aa1cD30585aAdB0C"),
  get_wallet_balance("0xD4689dF10d248FDDC4C16fb6Aa1cD30585aAdB0C", "eth"),
  get_wallet_balance("0xD4689dF10d248FDDC4C16fb6Aa1cD30585aAdB0C", "base"),
  # graphlet.eth
  get_eth_balance("0x1935b266057751504851166E805D2d3536F989B8"),
  get_wallet_balance("0x1935b266057751504851166E805D2d3536F989B8", "arbitrum"),
  # paulerdos.eth
  get_eth_balance("0x8c37d7078F1Dece30d257D4fbE07e10814CF4F9a"),
  # kramerstorage.eth
  get_eth_balance("0x0Db20C3BB8f286F3B0bd0a1653F7575E464D41c7"),
  get_wallet_balance("0x0Db20C3BB8f286F3B0bd0a1653F7575E464D41c7", "eth"),
  # zeusstorage.eth
  get_eth_balance("0x3a496A6C45dcCD44f474e45Fa208323dBC47f868"),
  # zeus.skinner.eth
  get_eth_balance("0xB234473A158bd059c628CeF4E016b6cc5a446B1d"),
  get_wallet_balance("0xB234473A158bd059c628CeF4E016b6cc5a446B1d", "eth"),
  get_wallet_balance("0xB234473A158bd059c628CeF4E016b6cc5a446B1d", "arbitrum"),
  # mulder.skinner.eth
  get_eth_balance("0xbF0eaD7fe9b0bED67a5Bd3e2CA477A57Fc0A6a16"),
  get_wallet_balance("0xbF0eaD7fe9b0bED67a5Bd3e2CA477A57Fc0A6a16", "eth")
  
) %>% 
  mutate(balance = round(balance, 5)) %>% 
  filter(!grepl("Get", symbol),
         !grepl("LPLido", symbol),
         !is.na(symbol)) %>% 
  distinct(wallet_address, balance, symbol)

wallet_summaries = wallet_balances %>% 
  group_by(symbol) %>% 
  summarise(balance = sum(balance)) 

wallet_balances
wallet_summaries
```















