---
title: "Untitled"
output: html_document
date: '2023-03-24'
---

```{r setup, include=FALSE}
rm(list = ls())
library("notionR")

PUT_YOUR_SECRET_HERE = ""



install.packages("devtools")
devtools::install_github("Eflores89/notionR") 

updateText <- function(secret, id, property_name, value){

  payload  <- sprintf(
    "{\"properties\":{\"%s\":{\"rich_text\":[{\"type\":\"text\",\"text\":{\"content\": \"%s\"}}]}}}",
    property_name, value
  )

  auth_secret <- paste0("Bearer ", secret)

  headers = c(
    `Authorization` = auth_secret,
    `Notion-Version` = '2022-02-22',
    `Content-Type` = 'application/json' )

  res <- httr::PATCH(url = paste0('https://api.notion.com/v1/pages/', id),
                     httr::add_headers(.headers = headers),
                     body = payload,
                     encode = "json")
  d <- httr::content(res)
  return(d)
}
```


```{r}
secret, id, property_name, value

updateText(secret = "",
           id = "941a5858fb4f4133a8acd22373beec2b",
           property_name = "Test",
           value = "Testing Again")

```

```{r}
NOTION_KEY = ""
```

```{js}
const { Client } = require('@notionhq/client');

const notion = new Client({ auth: process.env.NOTION_API_KEY });

(async () => {
  const response = await notion.users.list();
  console.log(response);
})();
```


```{r setup, include=FALSE}

library(httr)
library(jsonlite)
NOTION_KEY = ""

pb <- list(
  parent = list(database_id = "076fdef418e84f4b9cfbed1fcec0e7a6/query"),
  properties = list(
    Countries = list(
      title = list(
        list(text = list(content = "Australia"))
      )
    )
  )
)


ask <- GET(
  url = "https://api.notion.com/v1/databases/076fdef418e84f4b9cfbed1fcec0e7a6/query",
  add_headers("Authorization" = paste("Bearer", NOTION_KEY),
              "Notion-Version" = "2022-06-28"),
  body = pb,
  encode = "json")
stop_for_status(ask)
fromJSON(rawToChar(ask$content))


https://www.notion.so/brandonleekramer/076fdef418e84f4b9cfbed1fcec0e7a6?v=9772e28a4de9434984ca670bc1644729

```
```{r}

getNotionPage <- function(secret, id){

  url <- paste0("https://api.notion.com/v1/pages/", id)

  response <- httr::VERB("GET", url,
                         add_headers(Notion_Version = '2022-06-28', 
                                     Authorization = paste0('Bearer ', secret)),
                         content_type("application/octet-stream"),
                         accept("application/json"))
  r <- content(response, "text")
  r
}

getNotionPage("076fdef418e84f4b9cfbed1fcec0e7a6", "74438e02a7e94273bdb85db2a5677ff3?p=4c96938562a84ffbb3f40cf684945467&pm=s")

https://www.notion.so/brandonleekramer/Ideas-Journals-74438e02a7e94273bdb85db2a5677ff3?p=4c96938562a84ffbb3f40cf684945467&pm=s

```
